spring.application.name=distributed-url-shortener

server.port=${PORT:8080}

# MongoDB Atlas
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# Thymeleaf
spring.thymeleaf.cache=false

# Logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=500ms

# Cache
spring.cache.type=${SPRING_CACHE_TYPE:none}

# Base URL
app.base-url=${APP_BASE_URL:http://localhost:8080}