spring.application.name=Shortify

server.port=${PORT:8080}

# MongoDB Atlas
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/shortify}

# Thymeleaf
spring.thymeleaf.cache=false

# Logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO
logging.level.com.uday.urlshortener=INFO

# Redis
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:}
spring.data.redis.timeout=1000ms

# Cache
spring.cache.type=${SPRING_CACHE_TYPE:none}

# Base URL
app.base-url=${APP_BASE_URL:http://localhost:8080}

# SMTP Mail Configuration
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Actuator Health Check
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always